name: Build Docker Container

on:
  push:
    branches:
      - master
env:
  AWS_REGION: eu-central-1
  EKS_CLUSTER_NAME: demo 
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set short git commit SHA
        id: commit
        uses: prompt/actions-commit-hash@v2
      
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: igorkar/landing:${{ steps.commit.outputs.short }}

      - 
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.AWS_REGION}}

      - 
        name: Update kube config
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
        
      - 
        name: Deploy to EKS
        env:     
          IMAGE_TAG: ${{ steps.commit.outputs.short }}
        run: |
          sed -i.bak "s|DOCKER_IMAGE_TAG|$IMAGE_TAG|g" k8s/deployment.yaml && \
          kubectl apply -f k8s/deployment.yaml
